import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Practice Next JS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className='overflow-x-hidden' lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
